server:
  port: 8091

spring:
  datasource:
    db:
      open: true
      printTable: true
    hikari:
      allowPoolSuspension: false
      autoCommit: true
      connectionTestQuery: SELECT 1
      connectionTimeout: 30000
      driverClassName: com.mysql.cj.jdbc.Driver
      idleTimeout: 30000
      isolateInternalQueries: false
      jdbcUrl: jdbc:mysql://localhost:3306/test
      maxLifetime: 1800000
      maximumPoolSize: 15
      minimumIdle: 1
      password: wo123ni
      poolName: HikariCP1
      readOnly: false
      registerMbeans: false
      username: root
      validationTimeout: 5000
    table:
      name: db_entity
    type: com.zaxxer.hikari.util.DriverDataSource

logging:
  config: classpath:logback-boot.xml
  level:
    root: info
loadJar:
  open: true
  basePath: D:\jar